vulpixAI/vulpix-ai-api

- .github/workflows/trello-integration.yml
> Adiciona integração com trello

- src/main/java/com/vulpix/api/Controller/EmpresaController.java
- src/main/java/com/vulpix/api/Controller/IntegracaoController.java
- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
- src/main/java/com/vulpix/api/Controller/UsuarioController.java
- src/main/java/com/vulpix/api/Service/EmpresaService.java
> Corrige chamadas para identificar empresa pelo usuário autenticado

- database/script_vulpix_db.sql
> feat: adiciona entidade de criativos no script do banco

- database/script_vulpix_db.sql
- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
- src/main/java/com/vulpix/api/Entity/Publicacao.java
- src/main/java/com/vulpix/api/Repository/PublicacaoRepository.java
- src/main/java/com/vulpix/api/Service/Integracoes/Graph/PublicacaoService.java
- src/main/java/com/vulpix/api/Utils/Enum/StatusPublicacao.java
- src/main/java/com/vulpix/api/VulpixAiApiApplication.java
> feat: implementa lógica agendamento de publicação

- src/main/java/com/vulpix/api/Controller/EmpresaController.java
- src/main/java/com/vulpix/api/Controller/IntegracaoController.java
- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
- src/main/java/com/vulpix/api/Controller/UsuarioController.java
- src/main/java/com/vulpix/api/Dto/Criativo/CriativoMapper.java
- src/main/java/com/vulpix/api/Dto/Criativo/CriativoRequisicaoDto.java
- src/main/java/com/vulpix/api/Entity/Criativo.java
- src/main/java/com/vulpix/api/Repository/CriativoRepository.java
- src/main/java/com/vulpix/api/Service/EmpresaService.java
- src/main/java/com/vulpix/api/Service/Integracoes/AgentAi/CriativosService.java
- src/main/java/com/vulpix/api/Utils/Helpers/EmpresaHelper.java
> feat: implementa lógica para salvar criativos gerados a partir do Agent Ai

- src/main/java/com/vulpix/api/Controller/EmpresaController.java
- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
- src/main/java/com/vulpix/api/Controller/UsuarioController.java
> feat: att retorno status code HTTP usuario

- src/main/java/com/vulpix/api/Service/Integracoes/AgentAi/CriativosService.java
Única diferença no momento nesse ambiente dev é que ao invés de enviarmos a requisição ao Agent AI para gerar as imagens estaremos utilizando 4 imagens mockadas
> Subindo ambiente dev

- src/main/java/com/vulpix/api/Repository/CriativoRepository.java
- src/main/java/com/vulpix/api/Service/Integracoes/AgentAi/CriativosService.java
> fix: ordena listagem de criativos por mais recente

- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
- src/main/java/com/vulpix/api/Dto/Publicacao/GetPublicacaoDto.java
- src/main/java/com/vulpix/api/Repository/PublicacaoRepository.java
- src/main/java/com/vulpix/api/Service/Integracoes/Graph/PublicacaoService.java
> feat: implementa paginação na busca de posts + refatora lógica

- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
- src/main/java/com/vulpix/api/Repository/PublicacaoRepository.java
- src/main/java/com/vulpix/api/Service/Integracoes/Graph/PublicacaoService.java
> feat: filtragem por data para buscar post

- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
- src/main/java/com/vulpix/api/Repository/PublicacaoRepository.java
- src/main/java/com/vulpix/api/Service/Integracoes/Graph/PublicacaoService.java
- src/main/java/com/vulpix/api/Utils/Helpers/Exceptions/GlobalExceptionHandler.java
- src/main/java/com/vulpix/api/Utils/Helpers/Exceptions/InvalidDateFilterException.java
> Adiciona parametro dataFim na filtragem por data 

- src/main/java/com/vulpix/api/Controller/CriativoController.java
- src/main/java/com/vulpix/api/Repository/CriativoRepository.java
- src/main/java/com/vulpix/api/Service/Integracoes/AgentAi/CriativosService.java
> feat: filtragem por data get criativos

- database/script_vulpix_db.sql
- src/main/java/com/vulpix/api/Entity/PostInsights.java
- src/main/java/com/vulpix/api/Entity/Publicacao.java
> Implementa entidade Post Insight para gerenciar dashboard

- database/script_vulpix_db.sql
- src/main/java/com/vulpix/api/Entity/PostInsights.java
- src/main/java/com/vulpix/api/Repository/InsightRepository.java
- src/main/java/com/vulpix/api/Repository/IntegracaoRepository.java
- src/main/java/com/vulpix/api/Service/Integracoes/Graph/InsightService.java
- src/main/java/com/vulpix/api/Service/Integracoes/Graph/InsightsScheduler.java
> Implementa cron responsável por buscar métricas de post

- src/main/java/com/vulpix/api/Controller/EmpresaController.java
- src/main/java/com/vulpix/api/Dto/Empresa/EmpresaEditDto.java
- src/main/java/com/vulpix/api/Dto/Empresa/EmpresaMapper.java
- src/main/java/com/vulpix/api/Entity/Empresa.java
- src/main/java/com/vulpix/api/Entity/Usuario.java
- src/main/java/com/vulpix/api/Service/EmpresaService.java
> fix: update de empresa

- src/main/java/com/vulpix/api/Controller/UsuarioController.java
- src/main/java/com/vulpix/api/Dto/Usuario/AtualizarSenhaDto.java
- src/main/java/com/vulpix/api/Service/Usuario/UsuarioService.java
> feat :  implementa endpoint  de atualizar senhas

- src/main/java/com/vulpix/api/Dto/Empresa/EmpresaEditDto.java
- src/main/java/com/vulpix/api/Service/EmpresaService.java
- src/test/java/com/vulpix/api/Controller/EmpresaControllerTest.java
> fix: corrige testes unitários da classe empresa controller

- src/main/java/com/vulpix/api/Controller/DashboardController.java
- src/main/java/com/vulpix/api/Entity/PostInsights.java
- src/main/java/com/vulpix/api/Entity/Publicacao.java
- src/main/java/com/vulpix/api/Repository/DashboardRepository.java
- src/main/java/com/vulpix/api/Service/DashboardService.java
> feat: adiciona controller, service e repository para dash & get de ultima metrica de cada post

- src/main/java/com/vulpix/api/Config/WebConfig.java
- src/main/java/com/vulpix/api/Controller/DashboardController.java
- src/main/java/com/vulpix/api/Dto/Dashboard/DashKpiDto.java
- src/main/java/com/vulpix/api/Dto/Dashboard/PostInsightsDto.java
- src/main/java/com/vulpix/api/Repository/DashboardRepository.java
- src/main/java/com/vulpix/api/Service/DashboardService.java
- src/main/java/com/vulpix/api/Service/Integracoes/Graph/InsightsScheduler.java
> feat: adiciona lógica para buscar dados para o gráfico de linha

- src/test/java/com/vulpix/api/Service/IntegracaoServiceTest.java
> fix: corrigindo teste da classe IntegraçãoService

- src/main/java/com/vulpix/api/Controller/DashboardController.java
- src/main/java/com/vulpix/api/Controller/PagamentoController.java
- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
> feat: add swagger aos endpoints novos

- src/main/java/com/vulpix/api/Controller/IntegracaoController.java
- src/main/java/com/vulpix/api/Service/IntegracaoService.java
> feat: get integracao

- src/main/java/com/vulpix/api/Controller/PublicacaoController.java
> feat: adição de pilha e fila no endpoint de exportação de CSV
